name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grand permission to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test