name: CI
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $DATA | base64 -di > app/google-service.json

      - name: Grand permission to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test